### ISSUE TITLE
Not working? https://api.quotable.io/random does not load in browser

### ISSUE THREAD

**Issue by jastuccio** [lukePeavey/quotable#10]
I thought it would be pretty cool to use an API from another FCCer!  I was having trouble with the script and pointed my browser to several quotable.io domains.  They did not load.  Maybe this API got hammered with huge bandwidth?

**Comment by pomarka** [comment]
+1 I would also like to to use this API and it's not working :(

**Comment by Jazzyb21** [comment]
Yeah, it was working for a while but it randomly stopped.

**Comment by umn-aj** [comment]
Its down right now

**Comment by lukePeavey** [comment]
Hey everyone, sorry it took me a while to respond to this issue. 

I am making some deployment changes that should provide more consistent uptime and performance going forward.

Please try the API again and let me know if it working for you now!

thanks

**Comment by jastuccio** [comment]
Luke,

 I am really new to working with APIs. Not sure how to test this to determine what is goint on.  

It was giving me a CORS error on my macbook using both FF and chrome. I created [a repl.it](https://repl.it/@jastuccio/quotable-testl) and don't see anything in the console there either.

https://api.quotable.io/random does not load from ff, chrome, or opera

It is being reported as down: https://www.isitdownrightnow.com/api.quotable.io.html

**Comment by thebrucecgit** [comment]
+1 I would love to continue using this API

**Comment by lukePeavey** [comment]
@jastuccio 

The API is **not** down right now.

> It is being reported as down: https://www.isitdownrightnow.com/api.quotable.io.html

The website for this project is still under construction. So right now the root URL (api.quotable.io/) just responds with a `404` error.   

I just changed this so now the root url redirects to the GitHub repository (until website is complete)

**Comment by lukePeavey** [comment]
@jastuccio  

> I created a repl.it and don't see anything in the console there either.

I looked at your example on repl.it. There was a small error in your javascript (missing function call). Once you fix that, it works fine :)

Here is the updated version of your code ([try it on Repl.it](https://repl.it/@LUKEPEAVEY/quotable-test))

```js 
async function randomQuote() {
  const response = await fetch('https://api.quotable.io/random')
  const data = await response.json()
  console.log(`${data.content} —${data.author}`)
}

// + You need to call the function
randomQuote()
```

Here are a few more live examples you can try out:

[Basic Random Quote Example (CodePen)](https://codepen.io/lukePeavey/pen/RwNVeQG)

[React React Quote Example (CodeSandbox)](https://codesandbox.io/s/quotable-demo-react-e7zm1?fontsize=14&hidenavigation=1&module=%2Fsrc%2FApp.js&theme=dark)

**Comment by thebrucecgit** [comment]
@lukePeavey The website is still down, and is shown as is on isitdownrightnow.com

**Comment by Nepaltechguy2** [comment]
Is the server being hugged to death?

**Comment by lukePeavey** [comment]
@thebrucecgit

> turns out that it's just my home network that doesn't doesn't want to load the site for some reason – My bad!

OK, no worries

**Comment by lukePeavey** [comment]
I am going to close this issue now.  

@jastuccio, if your issue has not been addressed/resolved, please let me know and I will reopen this. 

If anyone else is having trouble, please create a new issue with a detailed description of the problem.

Thanks

**Comment by zakir360hossain** [comment]
I am having the same issue. I am trying to search this API (api.quotable.io/random) but it's throwing the following error:

This site can’t be reached
api.quotable.io’s server IP address could not be found.
DNS_PROBE_FINISHED_NXDOMAIN


*The confusing part is that it works perfectly when searched from a Windows machine, but not from mac.
I have tried the following steps, but so far unsuccessful:
1. Changing DNS to 8.8.8.8 and 8.8.4.4
2. Clearing browsing data and cache
3. Clearing DNS cache

I would really appreciate it if someone could help me with this.

**Comment by lukePeavey** [comment]
@zakir360hossain this issue has been closed in favor of #16. would you mind reposting your comment there?

**Comment by lukePeavey** [comment]
@zakir360hossain 


This has been fixed. See #16

**Comment by pranusri1903** [comment]
+1

**Comment by jshu000** [comment]
Hi @lukePeavey , It seems like API is down now.

**Comment by ohanz** [comment]
Hi @lukePeavey. please is your API down right now? Thanks in Advance!
source: function getQuote() {
    fetch("https://api.quotable.io/random")
        .then((response) => response.json())
        .then((data) => {
            quoteText.innerHTML = `"${data.content}" - ${data.author}`;
            getQuoteBtn.classList.remove("loading");
            getQuoteBtn.textContent = "Get Quote";
        }) ....

**Comment by ohanz** [comment]
please help @lukePeavey

**Comment by Idesta1** [comment]
It is not working....

**Comment by htooa2014** [comment]
I can't use api. it is still down. :'(

![Image](https://github.com/user-attachments/assets/7c1ef67d-9743-4b55-8ca2-a025a2a952e1)
