### ISSUE TITLE
Server is down 

### ISSUE THREAD

**Issue by umn-aj** [lukePeavey/quotable#11]
I am wondering when the server will be back ? Thanks

**Comment by lukePeavey** [comment]
It should be up and running now. Try it again and let me know if you are still having trouble.

**Comment by lukePeavey** [comment]
We have been having some issues with occasional downtime/slow response time effecting a small percentage of requests. 

I'm in the process of making some deployment changes that should address this and provide more consistent performance going forward. 

In the mean time, I just ran tests in Postman and the API is working. When you have a chance, please let me know if it is working on your end. Thanks!

**Comment by umn-aj** [comment]
Thank you very much. It works perfectly. I really appreciate your quick response.

**Comment by lukePeavey** [comment]
Awesome!  Let me know if this happens again

**Comment by AndyTempel** [comment]
I'm going to re-open because of this:
`curl: (6) Could not resolve host: api.quotable.io`
