### ISSUE TITLE
Endpoint with all the available Tags

### ISSUE THREAD

**Issue by UltiRequiem** [lukePeavey/quotable#117]
## Description

It would be very useful 🚀

**Comment by lukePeavey** [comment]
The `/tags` endpoint returns a list of all tags (see [documentation](https://github.com/lukePeavey/quotable#list-tags))

Usage ([try in browser](https://api.quotable.io/tags))

```http
GET /tags
```

**Comment by UltiRequiem** [comment]
didn't read that, thanks!

**Comment by lukePeavey** [comment]
No problem.
