### ISSUE TITLE
Application error 

### ISSUE THREAD

**Issue by khushalpatel1** [lukePeavey/quotable#131]
![image](https://user-images.githubusercontent.com/36466172/174321442-ff2de9a8-c284-4e4d-91c9-f4f31654b7ab.png)

**Comment by mcewball13** [comment]
I've got this too!

**Comment by lukePeavey** [comment]
I am looking into this. 

There is already an open issue for this problem: #132

**Comment by imanuelac** [comment]
We ran into the same here around 9AM EST today. We just addressed it on our end through a workaround (by removing the random quote API we use).

**Comment by lukePeavey** [comment]
@imanuelac  thanks for the additional information.  I'm sorry for the hassle this caused. 

I am still trying to figure out what caused this.

**Comment by lukePeavey** [comment]
This issue was resolved.
