### ISSUE TITLE
API is down

### ISSUE THREAD

**Issue by Oleg991JK** [lukePeavey/quotable#139]
> **Check the [current status](<[downfor.io/quotable.io](https://downfor.io/quotable.io)>) of the API servers. Does this show that the servers are down for everyone?**

yes or no

> **Provide any additional information that might be helpful**

**Comment by Gal1leo03** [comment]
Nope, i just checked and it seems to work.
I tried this ->  http://api.quotable.io/random

**Comment by lukePeavey** [comment]
Yeah the api is not down right now. @Oleg991JK have you tried the API again since you opened this? Let me know if it's working for you now.

**Comment by lukePeavey** [comment]
@Oleg991JK im going to close this since the api seems to be up now. Feel free to open another issue if you are still having trouble.
