### ISSUE TITLE
Better Documentation

### ISSUE THREAD

**Issue by humanfriend22** [lukePeavey/quotable#140]
I just started to use this API for my app and I found navigating through all the documentation in one README file a little complicated. I suggest using a static site generator like [Docusaurus](https://docusaurus.io/) or [Redocly](https://redocly.com/).

I can submit a PR if you're onboard.

**Comment by lukePeavey** [comment]
I was working a new documentation site powered by Stoplight. But haven't had time to finish it.

Quotable.stoplight.io

The documentation is generated from an openAPI schema and markdown files.  These are are in separate repository since they are not quite finished. 


Let me know what you think

**Comment by humanfriend22** [comment]
Wow! This is exactly what I was looking for. I think I can close this now.
