### ISSUE TITLE
API is down

### ISSUE THREAD

**Issue by mgon123** [lukePeavey/quotable#142]
Attempting to use this for a bootcamp project, but it seems to be down. Will it be coming back up soon?

**Comment by emmahsax** [comment]
Duplicate of https://github.com/lukePeavey/quotable/issues/143.

Also can confirm that the API is down for me. 
![image](https://user-images.githubusercontent.com/7562793/187819518-a2a8cc86-1752-4e4e-aea2-7889d12f4d83.png)

**Comment by lukePeavey** [comment]
# Fixed
