### ISSUE TITLE
[Feature Request] Web Links For Authors

### ISSUE THREAD

**Issue by HiltonGiesenow** [lukePeavey/quotable#15]
A lot of the authors in the quotes have bios that would be interesting to read, especially those on, say, Wikipedia. My feature request is to add these somehow (I guess in the Authors collection, if not into the quotes themselves (de-normalised, effectively, for ease of consumption).

Would you consider adding a "link" field (and possible even a photo url field) to the authors collection? I'd be happy with both pieces of work (A: adding the fields, and B: populating some of the authors themselves) if you'd like? Similar to my other request, I'd of course need access to the backend for 'B'.

**Comment by lukePeavey** [comment]
First, sorry it took me a while to respond to this issue! This is a great idea. I've wanted to do this for a while but had been putting it off. 

### Done: 

Added the following fields to all authors:

- `link` the person's wikipedia page.
- `bio` A short description about the person

I also cleaned up the authors collection. I removed all the duplicates, fixed incorrect and incomplete names, and removed unknown people with no wikipedia page or website.  

### TODO: 

- Add an `image` field to authors

It would be great to have a profile photo for each author. 

Let me know if you're still interested in working on this!

**Comment by LeCodeurSpatial** [comment]
It would be great to have an author's profile picture.  &#128077;
I would suggest to add url as image field and maintaining pinterest library of authors for uniformity. I am making pinterest library of authors with grayscale images for my project.
Also, data sample need an update with new records of 

- author bio and
- author web link.

**Comment by lukePeavey** [comment]
@LeCodeurSpatial I just updated the sample data.

**Comment by lukePeavey** [comment]
I am currently working on adding author images. I hope to have some time next weekend to work on this, we can discuss it more then :)

**Comment by LeCodeurSpatial** [comment]
@lukePeavey Nice! Surely will be up for discussion. :raised_hands:

**Comment by lukePeavey** [comment]
I think we should create a separate issue for the author images feature.

@LeCodeurSpatial 
would you mind opening a new issue?

**Comment by LeCodeurSpatial** [comment]
Done!

**Comment by dippas** [comment]
@lukePeavey  sorry to bother you again, but I have the same issue (as images) on how to get bio with any get request, could you please enlighten me  ?

**Comment by lukePeavey** [comment]
@dippas 

The `bio` field is included on authors returned by the `/authors` or `/authors/:id` endpoint.  If you are trying to get the bio for the author of a quote returned one of the quotes endpoints (`/quotes/ or `/random`) you would need to make a separate request to get author details using the author name or id. Let me know if this answers your question. 

Example ([try in browser](http://api.quotable.io/authors?name=Martin%20Luther%20King%20Jr.))

```HTTP 
GET /authors?name=Martin Luther King Jr.
```

**Comment by dippas** [comment]
@lukePeavey  thanks, I knew I was missing something basic .

But maybe adding this info in readme?

**Comment by lukePeavey** [comment]
We can definitely add something to the docs to clarify this.

**Comment by lukePeavey** [comment]
I'm going to close this issue. We have added the following fields to authors:

- `link` URL to the authors wikipedia page
- `bio` A brief, one paragraph bio of the author (source: wiki API)
- `description` A one-line description of the author, usually the person's nationality and primary occupation. For example, "Austrian Physicist" or "American Author" (source: wiki API / Google)

I am still working on adding profile images, but there is a separate issue for that now (#38)

Thanks to @HiltonGiesenow
