### ISSUE TITLE
API is down

### ISSUE THREAD

**Issue by pncsoares** [lukePeavey/quotable#157]
Hi 👋 
I am trying to request API but it is returning 503
![image](https://user-images.githubusercontent.com/37508158/192241555-10b1f67d-1cce-4834-8148-99ebe2c2fc1f.png)

**Comment by lukePeavey** [comment]
Thanks looking it

**Comment by pncsoares** [comment]
Thanks! 👍 
Nice work

**Comment by lukePeavey** [comment]
Thanks for reporting the issue
