### ISSUE TITLE
Unrelated: how to report the fake quotes?

### ISSUE THREAD

**Issue by nodtem66** [lukePeavey/quotable#159]
I accidentally found this one:
> I do not believe in a fate that falls on men however they act, but I do believe in a fate that falls on them unless they act. - Buddha

This quote is actually from an essay by G. K. Chesterton [ref 1](https://fakebuddhaquotes.com/i-do-not-believe-in-a-fate/), [ref 2](https://en.wikiquote.org/wiki/Gautama_Buddha#Misattributed), [ref 3](https://en.wikiquote.org/wiki/G._K._Chesterton)

Is there any idea to deal with invalid content in the database?
I think one way to do this is to report it in the GitHub issue.
But I'm not sure if it is a good idea or not.

**Comment by lukePeavey** [comment]
Thanks for reporting this! I'll definitely fix that. 

To answer your question: 

The api data is managed in a separate repository (linked below). Contributions are definitely welcome. You can  suggest changes (such as adding/removing/editing quotes by opening an issues. Or make changes directly  via pull request.


https://github.com/quotable-io/data
