### ISSUE TITLE
Error: A server with the specified hostname could not be found

### ISSUE THREAD

**Issue by jastuccio** [lukePeavey/quotable#16]
Luke,

  Sorry for not getting back to you before you closed issue 10.  Things have been a little crazy over the holidays.  I feel like quotable worked when you first linked the codepen and code sandbox, but after several more attempts it is not working for me over the past couple of days.

I tried FF Dev, Chrome and Safari browsers.

```shell
[Error] Error while parsing the 'sandbox' attribute: 'allow-presentation' is an invalid sandbox flag. (RwNVeQG, line 851)
[Error] Failed to load resource: A server with the specified hostname could not be found. (random, line 0)
[Error] Unhandled Promise Rejection: TypeError: A server with the specified hostname could not be found.
	(anonymous function) (RwNVeQG:66)
	asyncFunctionResume
	(anonymous function)
	promiseReactionJob
```

Here are some screenshots of the errors from Safari/codepen.
https://res.cloudinary.com/jastuccio/image/upload/v1577771339/quotable%20github%20errors/Screen_Shot_2019-12-31_at_00.24.40.png

https://res.cloudinary.com/jastuccio/image/upload/v1577771338/quotable%20github%20errors/Screen_Shot_2019-12-31_at_00.25.23.png

------ 
I found this in a search about the sandbox error:

> http://stackoverflow.com/a/33542435:
> 
> This error can be safely ignored, the script will continue to run fine. These are two new flags which have been implemented in Chrome 46 (the current stable release). If you're testing in a browser that doesn't support them, you'll see that error (which is really just a warning).
> 
> The allow-modals flag is required because Chrome will, by default, block modal dialogs within a sandboxed iframe. Adding this flag allows modals to work in your apps scripts

.

**Comment by lukePeavey** [comment]
I am looking into this... will respond shortly

**Comment by lukePeavey** [comment]
I'm still not sure what's causing this. This issue only effects certain users, not everyone.

I found that when I connect to VPN on my local machine, I get this error 100% of the time. I also get this error 100% of the time over certain wifi networks, but not others.

Will update you as soon as I have more info.

**Comment by lukePeavey** [comment]
If you are experiencing this issue you may see different error messages depending on what API client you are using. 

In chrome, 

```

**Comment by jastuccio** [comment]
Thanks Luke.  I'd like to help whoever diagnoses this.  Have you posted on dev.to or someplace to find someone?

* I am on MacOS 10.15.2
* disabled privacy badger for chrome
* turned VPN off and on
* tried Opera

Here is a screenshot of the error from the codepen sample.  

<img width="722" alt="Screen Shot 2020-01-07 at 22 19 41" src="https://user-images.githubusercontent.com/2707569/71947760-db782f00-319b-11ea-9992-92e048797940.png">

Its after 10pm here and I am out of brainpower for the night. 😊

**Comment by lukePeavey** [comment]
Try using this domain and see if it works as expected. 

https://quotable.dev/random

**Comment by lukePeavey** [comment]
@jastuccio 

There was an issue with the DNS configuration for the quotable.io domain which was preventing it from resolving with DNSSEC-aware resolvers. 

Fixing that seems to have solved the problem. The API now works from any network/device and while connected to VPN. Please confirm if this is true on your end.

**Comment by lukePeavey** [comment]
Also, these sites are no longer showing api.quotable.io as down...

https://www.isitdownrightnow.com/api.quotable.io.html

https://downforeveryoneorjustme.com/api.quotable.io

**Comment by jastuccio** [comment]
Luke, 

Both demos and the url are working for me today.  I tested with the VPN also no issues.  Good job!

[https://api.quotable.io/random](https://api.quotable.io/random)

[codesandbox demo](https://codesandbox.io/s/quotable-demo-react-e7zm1?fontsize=14&hidenavigation=1&module=%2Fsrc%2FApp.js&theme=dark)

[codepen demo](https://codepen.io/lukePeavey/pen/RwNVeQG)

**Comment by pea-nut-z** [comment]
@lukePeavey I am experiencing the following error message when connected to a particular network. Just like what @jastuccio had.

GET https://api.quotable.io/random net::ERR_NAME_NOT_RESOLVED

Please let me know if you need other info.

**Comment by noonasGit** [comment]
same here:
nslookup api.quotable.io
Server:		192.168.86.1
Address:	192.168.86.1#53

** server can't find api.quotable.io: SERVFAIL
I have tried a few different DNS servers, none if them can resolve it.

**Comment by noonasGit** [comment]
A while back - I started to safeguard for a quote server outage.
I saved the quote each time I called it, so that I could read a "cached version" should internet be down or service not accessible. I also use this as an option not to overload the quote severs.

have a look here: https://github.com/noonasGit/quote_client

**Comment by denys-duchier** [comment]
that issue is still a problem today (fails on my wired network, but works on my phone with wifi turned off.... weird)

**Comment by EssamHandok** [comment]
> that issue is still a problem today (fails on my wired network, but works on my phone with wifi turned off.... weird)

did you solve it ?

**Comment by JulioIzquierdo** [comment]
I'm experiencing the same issue as @denys-duchier.  Has there been any updates as of late?
i greatly appreciate it!
