### ISSUE TITLE
API is down

### ISSUE THREAD

**Issue by FrozenSamurai** [lukePeavey/quotable#162]
Heroku Server error on fetch request.

![image](https://user-images.githubusercontent.com/76254854/204050292-41943512-9ffe-4550-993f-164748a769b8.png)

**Comment by alejandrardecajal** [comment]
Maybe is because Heroku is no longer free. Please, I need the quotes to work! thank you!

**Comment by lukePeavey** [comment]
It's not deployed on free a server.

**Comment by lukePeavey** [comment]
I'm not not sure why it's down, I'll look into it

**Comment by lmeraki** [comment]
it's live now, thank you

**Comment by alejandrardecajal** [comment]
Now it is down again.

**Comment by lukePeavey** [comment]
Fixed, for now. 

There has been some downtime today due to a significant increase in request volume. If this continues to be a problem we can add a rate limit or require some form of authentication to prevent abuse.

**Comment by FrozenSamurai** [comment]
Thank you @lukePeavey

**Comment by lukePeavey** [comment]
The api is down again, see #163 for updates
