### ISSUE TITLE
Request for permission to use API in website.

### ISSUE THREAD

**Issue by MansuriHarun** [lukePeavey/quotable#170]
Dear API maintainers,

I hope this message finds you well. I am writing to inquire about the possibility of using your Quote Generator API in a website I am developing. I have thoroughly researched your API and I am impressed with its functionality and capabilities.

My website is focused on providing users with inspiring quotes and I believe your API would greatly enhance the user experience by providing a diverse selection of quotes. I would like to request your permission to use your Quote Generator API in my website.

I understand the importance of proper API usage and I assure you that I will adhere to the API's terms of service. I have also read and understand the API's usage policies, including the requirement for an API key, usage limits, and any other relevant information.

If you could provide me with more information on the process for obtaining an API key and any other requirements for using the API, I would greatly appreciate it.

Thank you for your time and consideration. I look forward to the opportunity to use your API and provide a valuable service to my website users.

Best regards,
[Harun Mansuri]

**Comment by lukePeavey** [comment]
Hi, thanks for inquiring about this.  You are welcome to use the API on your website.  There are no specific restrictions on how the API can be used.  You can use for commercial or non commercial projects, etc.  Attribution is appreciated, but not required. 

As far as API keys... 

The API does not require authentication, it's open to the public. So you don't need an API key to use it. 

There is a rate limit of 200 requests per minute, per IP address.  But that is the only restriction. 

Let me know if you have any other question / comments.

**Comment by lukePeavey** [comment]
I'm going to close this, but feel free to comment if you have any additional questions
