### ISSUE TITLE
API is down

### ISSUE THREAD

**Issue by rishabh2002chauhan** [lukePeavey/quotable#171]
Dear API maintainers,

I hope this message finds you well. I am writing to tell the API has not been responding since tomorrow. 
I would like to know if you are experiencing this issue or not.

**Comment by rishabh2002chauhan** [comment]
![Screenshot_2023-02-13-12-36-57-434_com.android.chrome.jpg](https://user-images.githubusercontent.com/71535168/218392872-efd29304-af58-4a39-a968-541b581450f9.jpg)

Screenshot for above issue

**Comment by aziham** [comment]
Same issue:

![image](https://user-images.githubusercontent.com/94932043/218401383-6831f729-52ca-4602-a51a-e25bf4e8d148.png)

**Comment by rishabh2002chauhan** [comment]
the API is working fine on my friend's phone at his house but it's not working on any device at my home.

**Comment by raghvendra007** [comment]
No, it's not working

> the API is working fine on my friend's phone at his house but it's not working on any device at my home.

**Comment by lukePeavey** [comment]
Thanks for reporting this. Working on it

**Comment by lukePeavey** [comment]
The issue has been fixed. Should be working again now

**Comment by raghvendra007** [comment]
> The issue has been fixed. Should be working again now

still not working

**Comment by raghvendra007** [comment]
#
<img width="1440" alt="Screenshot 2023-02-14 at 11 51 30 AM" src="https://user-images.githubusercontent.com/49129140/218656090-59e742d7-5557-4fe3-b28a-8ecf45dcf61e.png">

**Comment by lukePeavey** [comment]
<img width="1149" alt="image" src="https://user-images.githubusercontent.com/8286271/218664022-ef563e9b-2a7e-4233-b305-734d1c0a4040.png">

It might take a few hours for the changes to propagate everywhere.
