### ISSUE TITLE
Querying for author or quotes returns unexpected empty array

### ISSUE THREAD

**Issue by eliasljubec** [lukePeavey/quotable#179]
**Describe the bug**
When I query for either an author or quote, I receive an empty array as a result. This outcome is unexpected, given that I have used the example links provided in the documentation and also tested with generic search terms, but still encountered the same issue.

**To Reproduce**
1. Open an API client (Postman or Chrome)
2. Make the following API request

```HTTP
GET https://api.quotable.io/search/quotes?query=life+happiness
GET https://api.quotable.io/search/authors?query=einstein
```

**Expected Response**
Should not be empty

**Actual Response**
```
{
count: 0,
totalCount: 0,
page: 1,
totalPages: 0,
lastItemIndex: null,
results: [ ]
}
```

**Comment by lukePeavey** [comment]
Thanks for reporting. Working on fixing this issue

**Comment by lukePeavey** [comment]
This has been fixed.
