### ISSUE TITLE
Query parameter to enhance the usability of the /random endpoint

### ISSUE THREAD

**Issue by eliasljubec** [lukePeavey/quotable#180]
## Description

To improve the usability of the `/random` endpoint, a `query` parameter could be introduced alongside the existing `tags` parameter. While tags are currently used to retrieve _specific_ random quotes, a `query` parameter would allow users to search for quotes that match specific keywords.

This feature would make it easier for users to find quotes that align with their needs. 
For example, if a user is interested in quotes related to "life" and "happiness", they could use the following URL to retrieve a random selection of quotes:

`GET https://api.quotable.io/quotes/random?query=life happiness&limit=3`

**Comment by lukePeavey** [comment]
This is a great idea!! 


We could use the same search same configuration as the `/search/quotes` endpoint.  This does a full text search of the `content`, `author`, and `tags` fields.  It will include all quotes that match at least one word in the query.   

So you could get random quotes matching keywords 

```HTTP
GET https://api.quotable.io/quotes/random?query=life happiness&limit=3
```

You  could also get random quotes by author(s) without knowing the exact author name or id
```HTTP
GET https://api.quotable.io/quotes/random?query=einstein&limit=3
```

I think this parameter would have to mutually exclusive

**Comment by lukePeavey** [comment]
@eljubec did you have a chance to check out PR #181?

Let me know if you have any thoughts.

**Comment by eliasljubec** [comment]
Hey @lukePeavey, thanks for the effort, looks very good! 💯
