### ISSUE TITLE
Tags are case sensitive

### ISSUE THREAD

**Issue by ItzNotABug** [lukePeavey/quotable#182]
**Describe the bug**
The api returns a `404` if the tags are lowercased, only returns a quote if the initial character is uppercased.

**To Reproduce**
1. Using the url like: https://api.quotable.io/random?tags=Wisdom will return a random quote with specified tag.
2. Using the lowercased tag like this: https://api.quotable.io/random?tags=wisdom, this returned a 404.

**Expected Response**
A quote :)

**Actual Response**
```json
{"statusCode":404,"statusMessage":"Not Found"}
```

**Comment by lukePeavey** [comment]
Thanks for the report.   Fixing this now

**Comment by lukePeavey** [comment]
Fixed  85939ba63a942f744fbf6a70db39f5a942e0cae4
