### ISSUE TITLE
API is Down

### ISSUE THREAD

**Issue by danhddao1997** [lukePeavey/quotable#186]
Hello,

I'm currently implementing the API from quotable for my project. However when I fork from the Postman, the API works normally but when I'm using in my front-end project, it keeps being failed to fetch.

I'm working with basic a sample React application. I also have check with the example website in CodeSandbox.

**Comment by Suhail-007** [comment]
I thought i was the only one facing this issue, one of my app using 'quotable api' stop working.

**Comment by neksodebe** [comment]
I get this error while using curl
![image](https://user-images.githubusercontent.com/64833558/236695797-9968a0fc-42c3-4038-a4b0-dbc8729c0582.png)

**Comment by Suhail-007** [comment]
> I get this error while using curl ![image](https://user-images.githubusercontent.com/64833558/236695797-9968a0fc-42c3-4038-a4b0-dbc8729c0582.png)

Yea, api is not working request is not resolving

**Comment by lukePeavey** [comment]
Thanks for reporting. The API is partially down right now due to an expired DNSSEC key. Will fix asap

**Comment by lukePeavey** [comment]
Working on this now, should be resolved shortly

**Comment by lukePeavey** [comment]
## Fixed At 5:15 PM EST 

Hey everyone, this issue has been fixed. The API should be working again.  It may take a few hours for the changes to propagate in some locations, so if you are still having issue, check back in a little while.  

Sorry for the inconvenience. 

<img width="1081" alt="image" src="https://user-images.githubusercontent.com/8286271/236702866-a40c2b76-6f04-4203-8d49-c7a226d9e206.png">

<img width="537" alt="image" src="https://user-images.githubusercontent.com/8286271/236702919-b612d5e0-608b-4194-8546-b22403f9c78f.png">
