### ISSUE TITLE
[Feature Request] Get a quote with a maximum length

### ISSUE THREAD

**Issue by Dragonsight91** [lukePeavey/quotable#19]
**The Request**
What would be really nice is the ability to use a GET parameter to specify the maximum or minimum length of a desired quote. 
like this:

**Expected Behavior:**
`https://api.quotable.io/random?maxlen=50` => gives a random quote with a length of no more than 50 characters
`https://api.quotable.io/random?minlen?=20` => gives a quote with at least 20 char length.
and so on. 

**Suggestions**
Adding a length entry and then sorting the database by length. Now get the section that has 0 to n characters and select a random one.

**Comment by lukePeavey** [comment]
I think this would be a great feature to add!  If you would like to work on it you're welcome to submit a PR. Totally up you.

**Comment by Dragonsight91** [comment]
Although my experiences with Node and mongodb are quite limited, i'll most definitely try.
