### ISSUE TITLE
API is down

### ISSUE THREAD

**Issue by rogerwarr** [lukePeavey/quotable#191]
API is down for about 2 days.

Can you please fix it asap?
Thank you

**Comment by NeerajLoserSharma** [comment]
Hi @lukePeavey sir 🙏🙏! The API's been down for quite a long time (almost over 2 days as of I'm reporting) now and because of that I'm facing problems in my web app. Can you please look into the issues and fix them as soon as possible?

Thanks a lot in advance 🙏.

**Comment by TheSegtendo** [comment]
I dont think the api is down, my app wont get quotes for a few days now, but the test version (same code) of it DOES get the quotes, manually going to the endpoint also gives a result, so i think something went wrong and ppl got either wrongly rate limited or flat out black listed.

**Comment by rogerwarr** [comment]
> I dont think the api is down, my app wont get quotes for a few days now, but the test version (same code) of it DOES get the quotes, manually going to the endpoint also gives a result, so i think something went wrong and ppl got either wrongly rate limited or flat out black listed.

I tried typing the url in chrome, but there is nothing there, i tried also using postman but no result too, also they didn't mention anything about rate limited or something like that.

I have 2 questions:
1. What do you mean by "manually going to the endpoint"?
2. What language did you use in your app?

**Comment by TheSegtendo** [comment]
> > I dont think the api is down, my app wont get quotes for a few days now, but the test version (same code) of it DOES get the quotes, manually going to the endpoint also gives a result, so i think something went wrong and ppl got either wrongly rate limited or flat out black listed.
> 
> I tried typing the url in chrome, but there is nothing there, i tried also using postman but no result too, also they didn't mention anything about rate limited or something like that.
> 
> I have 2 questions:
> 
> 1. What do you mean by "manually going to the endpoint"?
> 2. What language did you use in your app?

By manually I mean using a browser, works without issue. My app is in python. It's a discord bot, would tell a daily quote and whatnot. Bot in live server doesn't get any quotes. Same bot, same code, but on a different machine (for testing) gets the quote without issue.

**Comment by rogerwarr** [comment]
> > > I dont think the api is down, my app wont get quotes for a few days now, but the test version (same code) of it DOES get the quotes, manually going to the endpoint also gives a result, so i think something went wrong and ppl got either wrongly rate limited or flat out black listed.
> > 
> > 
> > I tried typing the url in chrome, but there is nothing there, i tried also using postman but no result too, also they didn't mention anything about rate limited or something like that.
> > I have 2 questions:
> > 
> > 1. What do you mean by "manually going to the endpoint"?
> > 2. What language did you use in your app?
> 
> By manually I mean using a browser, works without issue. My app is in python. It's a discord bot, would tell a daily quote and whatnot. Bot in live server doesn't get any quotes. Same bot, same code, but on a different machine (for testing) gets the quote without issue.

I'd appreciate it if you could send to me what you exactly write in your browser's address bar, 'cause it might be forbidden in some regions, and can you plz recheck it from the browser?

**Comment by TheSegtendo** [comment]
> > > > I dont think the api is down, my app wont get quotes for a few days now, but the test version (same code) of it DOES get the quotes, manually going to the endpoint also gives a result, so i think something went wrong and ppl got either wrongly rate limited or flat out black listed.
> > > 
> > > 
> > > I tried typing the url in chrome, but there is nothing there, i tried also using postman but no result too, also they didn't mention anything about rate limited or something like that.
> > > I have 2 questions:
> > > 
> > > 1. What do you mean by "manually going to the endpoint"?
> > > 2. What language did you use in your app?
> > 
> > 
> > By manually I mean using a browser, works without issue. My app is in python. It's a discord bot, would tell a daily quote and whatnot. Bot in live server doesn't get any quotes. Same bot, same code, but on a different machine (for testing) gets the quote without issue.
> 
> I'd appreciate it if you could send to me what you exactly write in your browser's address bar, 'cause it might be forbidden in some regions, and can you plz recheck it from the browser?

Not forbidden, since it works, it only does NOT work on the live bot. Note it has been working for a few weeks and only recently stopped. I'll try post more info tomorrow when I'm back at my pc.

**Comment by rogerwarr** [comment]
> > > > > I dont think the api is down, my app wont get quotes for a few days now, but the test version (same code) of it DOES get the quotes, manually going to the endpoint also gives a result, so i think something went wrong and ppl got either wrongly rate limited or flat out black listed.
> > > > 
> > > > 
> > > > I tried typing the url in chrome, but there is nothing there, i tried also using postman but no result too, also they didn't mention anything about rate limited or something like that.
> > > > I have 2 questions:
> > > > 
> > > > 1. What do you mean by "manually going to the endpoint"?
> > > > 2. What language did you use in your app?
> > > 
> > > 
> > > By manually I mean using a browser, works without issue. My app is in python. It's a discord bot, would tell a daily quote and whatnot. Bot in live server doesn't get any quotes. Same bot, same code, but on a different machine (for testing) gets the quote without issue.
> > 
> > 
> > I'd appreciate it if you could send to me what you exactly write in your browser's address bar, 'cause it might be forbidden in some regions, and can you plz recheck it from the browser?
> 
> Not forbidden, since it works, it only does NOT work on the live bot. Note it has been working for a few weeks and only recently stopped. I'll try post more info tomorrow when I'm back at my pc.

I know, it was working fine, but after some time it stopped.

**Comment by TheSegtendo** [comment]
But like I said, still works on test environment. That's why I was thinking it's now likely a blocked IP than anything else.

**Comment by rogerwarr** [comment]
> But like I said, still works on test environment. That's why I was thinking it's now likely a blocked IP than anything else.

Impossible, I tested it in an rdp server in netherlands, but still same problem

**Comment by TheSegtendo** [comment]
> > But like I said, still works on test environment. That's why I was thinking it's now likely a blocked IP than anything else.
> 
> Impossible, I tested it in an rdp server in netherlands, but still same problem

It was like I said this morning. Will test again tomorrow

**Comment by TheSegtendo** [comment]
Ok I found something very interesting. I was trying the same I was song yesterday. Live bot doesn't get quote, test and browser do. Same thing today, I could get quote no issue, just not in the live bot. Then I tried using my phone's browser to get quote and... It didn't work. Then I remember I was using a private dns to block ads, so I disabled that and it works again. So maybe the API IP is being blocked somewhere. FYI my live server is also Netherlands.

**Comment by rogerwarr** [comment]
Intresting, anyway we must wait for @lukePeavey to fix this issue.

**Comment by japandotorg** [comment]
yeah, the API seems to be online, but at the same time it's throwing out name resolution errors.
![image](https://github.com/lukePeavey/quotable/assets/78662983/d6639b7c-e8ee-49e6-9994-4d040df0a3f8)

**Comment by rogerwarr** [comment]
Strange, that means that the API is not fully down.

**Comment by mathvdh** [comment]
There is definitively some problem on api.quotable.io

See : [https://mxtoolbox.com/SuperTool.aspx?action=dns:api.quotable.io&run=toolpage](https://mxtoolbox.com/SuperTool.aspx?action=dns:api.quotable.io&run=toolpage)

**Comment by TheSegtendo** [comment]
Yes, like @japandotorg said, there is some name resolution issues. That is why it gets blocked by some firewalls, but not others.

**Comment by NeerajLoserSharma** [comment]
Does anyone have any idea about till when the API will be fully functional?

**Comment by SynapseScribe** [comment]
it s DNS propagation issue
https://www.whatsmydns.net/#A/api.quotable.io => some parts of the world fail resolving the domain
https://browserleaks.com/ip/api.quotable.io => Lookup Error: failed to resolve domain name

i tried both cloudflare and quad9 but cannot resolve api.quotable.io
on tor browser this domain is resolved however.

this means better nameservers must be used, or send an email to whoever is hosting this

**Comment by rogerwarr** [comment]
A week has passed, but still no response from the repo owner

**Comment by TheSegtendo** [comment]
Either owner is on vacation, or the project is abandoned. Either way there are many other alternatives to this.

**Comment by lukePeavey** [comment]
Apologies for the slow response time!  I was on vacation the past two weeks and not able to deal with this until I returned.

**Comment by lukePeavey** [comment]
The issue has been resolved on the API is back up.

**Comment by NeerajLoserSharma** [comment]
> The issue has been resolved on the API is back up. 

Thanks.

**Comment by SynapseScribe** [comment]
Thanks !! What exactly happened?

**Comment by rogerwarr** [comment]
> The issue has been resolved on the API is back up.

Thank you very much

**Comment by mathvdh** [comment]
Thank you !! And I don't think you need to apologise, thank you for providing this service for free to the community !
