### ISSUE TITLE
API is down | Invalid Certificate

### ISSUE THREAD

**Issue by Anas-Dew** [lukePeavey/quotable#204]
![image](https://github.com/lukePeavey/quotable/assets/96536838/7ee163d0-5810-43b9-98eb-c280a44031af)

Due to invalid certificate, API is down

**Comment by clowa** [comment]
The Let's Encrypt Certificate has expired on 10.02.2024.

**Comment by Anas-Dew** [comment]
So lets renew it

**Comment by lukePeavey** [comment]
# Update - Working on It 

Hey guys.  I'm looking into this now. I'm not sure what happened. I the SSL certificate is automatically managed by hosting provider.  I'm working on it, I will post an update on this issue as soon as I have more info.  I am going to close all duplicate issues and will post updates here.  


Sorry for the inconvenience

**Comment by lukePeavey** [comment]
# Update - Fixed

Should be all set now. Sorry about the downtime.  It may take a couple hours for the changes to propagate depending on your location

**Comment by shinziki** [comment]
Thank you for considering to fix the issue

**Comment by Anas-Dew** [comment]
Thanks buddy, I've been creating a cool stuff with it.

**Comment by JustVugg** [comment]
the problems with the https certificate are still there and there are no ways to connect except in http but it is not really safe. Anyway thanks a lot for your work and for this project!

**Comment by JustVugg** [comment]
@lukePeavey

**Comment by KevinMa-Toptal** [comment]
bump - still down for daily quotes
