### ISSUE TITLE
API is down (cert expired)

### ISSUE THREAD

**Issue by Khobalt** [lukePeavey/quotable#207]
The cert for the API has expired.

**Comment by MilesWK** [comment]
Will you get a new one? And also... the API works but it shows the website is unsafe when I use the API via `fetch()`

**Comment by AmrTamer23** [comment]
Hi guys, temporarily you can pass in to the https agent to not check for SSL certificate.  
![image](https://github.com/lukePeavey/quotable/assets/122938074/761846e1-8730-4cd8-9c15-3117b8ea5603)
IMPORTANT NOTE: It's not working on chrome but works well with firefox.

**Comment by lukePeavey** [comment]
Ok will fix asap!

**Comment by lukePeavey** [comment]
@me

**Comment by lukePeavey** [comment]
I'm working on this now.  Going to close this issue as a duplicate, check issue #204 for updates on this
