### ISSUE TITLE
Implement Automatic SSL Renewal

### ISSUE THREAD

**Issue by MullerIsabella** [lukePeavey/quotable#210]
## Implement Automatic SSL Renewal

At the time of writing, the SSL certificate for api.quotable.io is expired (#204, #207, #209).

This seems to be a [recurring](https://github.com/SilentVoid13/Templater/issues/1320#issuecomment-1937812168) issue.

Implementing auto-renewal would be very useful in reducing certificate-based API downtimes.

One way is to incorporate with the API server an open-source tool like [NGINX Proxy Manager](https://nginxproxymanager.com/), as a reverse proxy for api.quotable.io, since certificate management and auto-renewal for Let's Encrypt certificates are built-in. 

Alternatively, utilizing [Cron](https://crontab.guru/) with Certbot on the API server, the Let's Encrypt SSL certificate(s) can be renewed at a set interval (such as monthly).

By implementing automatic SSL renewal, manual maintenance as well as service disruptions can be minimized.

**Comment by vpodolyan** [comment]
It would be nice to have or at least renew it manually so far

**Comment by lukePeavey** [comment]
I'm working on this now.  Going to close this issue as a duplicate, check issue #204 for updates on this

**Comment by MarketingPip** [comment]
@lukePeavey - just a thank you for your work + implementing this! (This crashed / messed up little project of mine that uses this!). If interested see [here](https://github.com/imageplaceholder/quotes)

Cheers 🍺
