### ISSUE TITLE
[Docs] Update documentation for tags endpoint

### ISSUE THREAD

**Issue by lukePeavey** [lukePeavey/quotable#25]
**1.  Update documentation for tags endpoint**

[README#get-tags](https://github.com/lukePeavey/quotable#get-tags) should include a section with the following query parameters

- param: sortBy
   type: `enum: ["name", "quoteCount"]`
   description: The field used to sort tags. Default is name.

- param: sortOrder
   type: `enum: ["asc", "desc"]`
   description: The order in which results are sorted. Default order depends on the sortBy field.

**2. Add the tags endpoint to the table of contents**

**Comment by raxraj** [comment]
Hey @lukePeavey, as I can see in the README, I believe it is still open. Shall I proceed?

**Comment by lukePeavey** [comment]
Closed by #44
