### ISSUE TITLE
[Feature] Search quotes

### ISSUE THREAD

**Issue by lukePeavey** [lukePeavey/quotable#31]
# Description

An API method to search quotes. It should allow people to search for quotes by `content`, `author`, and possibly `tags`.  Ideally, search results should be sorted by relevance. 

## API

```HTTP
GET /search/quotes
```

**Query Params**

| param | type     | Description                                                   |
| :---- | :------- | :------------------------------------------------------------ |
| query | `String` | The string to search for                                      |
| limit | `Int`    | The number of authors to return per request. (for pagination) |
| skip  | `Int`    | The number of items to skip (for pagination)                  |

## Use Cases

**1. Search for a specific quote or phrase**

Ideally, this should work even if the query does not exactly match the quote

```HTTP
GET /search/quotes/?query=a divided house wont stand
```
```HTTP
GET /search/quotes/?query=divided house
```
Should both return the following quote
```json
"A house divided against itself will not stand"
```

**2. Search for quotes containing a keyword**
```HTTP
GET /search/quotes/?query=love
```
Should return all quotes containing the word "love"

**3. Search for quotes by author name**
```HTTP
GET /search/quotes/?query=Lincoln
```

**Comment by marekdano** [comment]
@lukePeavey how do you expect the search should work when there is one search endpoint with the general `query` param? When we get `query`, should we search first by `content`, `author`, and then `tags` and display the quotes in this order?

**Comment by mitramejia** [comment]
@lukePeavey or @marekdano is there a reason to have a `search/quotes?query=test` instead of `quotes?query=test`? I'm not very experienced in REST API design so  I might be missing something obvious, please let me know what do you think.

**Comment by marekdano** [comment]
@mitramejia I'd prefer to have an endpoint of `search/...`. But I wanted to know in my comment above, what to search. Will the API search for quotes by their content only? Or we'll have the endpoint which will cover also search for quotes by the content of `author` name, and `tags` names? So when we enter a `query` term, the API checks a quote content, author, and tags or just quote content?
What do you think @lukePeavey

**Comment by lukePeavey** [comment]
@marekdano to answer your initial question...

There are a few different ways we could implement the search feature...

### Text Search

Initially, I was thinking that this method would search by content, author name and tags simultaneously and sort the results based on text matching score.  This would be useful for a search bar where the user could search for quotes by typing in a person's name, keywords, or part of a quote and see matching results. 

This can be implemented using [text search](https://docs.mongodb.com/manual/text-search/)

**Limitations**

- On each collection, you can only search one set of fields, which are defined in a [text index](https://docs.mongodb.com/manual/core/index-text/#index-feature-text). So its not possible to search different fields based on API parameters. 

### Atlas Search 

Another possibility that we could consider (maybe down the road) is using [Atlas Search (beta)](https://docs.atlas.mongodb.com/atlas-search/), which is the newer version of text search.

> MongoDB’s Atlas Search feature offers fine-grained text indexing to enable advanced search functionality without any additional management required. Atlas Search provides options for several kinds of text analyzers, score-based results ranking, and a rich query language.

With Atlas search, we could have an additional param that lets you specify which field(s) to search. 

```HTTP
GET /search/quotes?query=Lincoln&fields=author
```

**Caveats**

- This feature is only supported on [Atlas](https://www.mongodb.com/cloud/atlas), MongoDB's cloud platform.

**Comment by lukePeavey** [comment]
@mitramejia 

>  is there a reason to have a search/quotes?query=test instead of quotes?query=test? 

Either way would work, but I think it makes sense to have separate search endpoints.

**Comment by lukePeavey** [comment]
@marekdano @mitramejia Let me know what you guys think.
