### ISSUE TITLE
Bug report - Server not found.

### ISSUE THREAD

**Issue by RutvikJ77** [lukePeavey/quotable#46]
Cannot access the specified API URL anymore. As well as the try in browser links in readme are currently dead.
![Screenshot 2021-01-27 at 4 52 29 PM](https://user-images.githubusercontent.com/45565999/105984396-10656580-60c0-11eb-8dad-d5fb30f483fd.png)

**Comment by techmaharaj** [comment]
Same error at my end too.

**Comment by raxraj** [comment]
@lukePeavey, We need you here man!

http://api.quotable.io/

![image](https://user-images.githubusercontent.com/41513907/106095421-ccbf3a00-6159-11eb-8703-9cdde22b33a9.png)

**Comment by sheshnathiicmr** [comment]
+1

**Comment by lukePeavey** [comment]
Working on this now!

**Comment by lukePeavey** [comment]
This has been fixed. Sorry for the inconvenience everyone. Please let me know if are still having trouble reaching the server.
