### ISSUE TITLE
List Quotes: Max query is wrong in documentation

### ISSUE THREAD

**Issue by dippas** [lukePeavey/quotable#49]
In the documentation you have `Max: 100`
![image](https://user-images.githubusercontent.com/10220287/109394251-f799db00-791d-11eb-8a41-65639caefcad.png)

But  if we set `https://api.quotable.io/quotes?limit=100` (or any number above 50, the count will always be 50.

![image](https://user-images.githubusercontent.com/10220287/109394312-48113880-791e-11eb-97c2-43a5f24544b6.png)

Can the limit be 100 or even the `totalCount` ?

**Comment by lukePeavey** [comment]
The limit was suppose to be `100`. It looks like this got changed by mistake at some point.  I'd rather not remove the limit entirely, but we can increase it to 150 if you want. 

Would you like to submit a PR to make this change? If not, I can take care of it. 

## Steps to fix

### List Quotes Endpoint

To change the maximum limit, edit this line of code. 

https://github.com/lukePeavey/quotable/blob/164119765736a02ee4dd6bc817e3eda74afc9b63/src/controllers/quotes/listQuotes.js#L46

```diff
-limit = clamp(parseInt(limit), 0, 50) || 20 
+limit = clamp(parseInt(limit), 0, 150) || 20 
```

### List Authors Endpoint

https://github.com/lukePeavey/quotable/blob/164119765736a02ee4dd6bc817e3eda74afc9b63/src/controllers/authors/listAuthors.js#L35

```diff
-limit = clamp(parseInt(limit), 1, 50) || 20 
+limit = clamp(parseInt(limit), 1, 150) || 20 
```

### Docs

Update the README

**Comment by dippas** [comment]
@lukePeavey  PR made
