### ISSUE TITLE
Suggestion: Add API for getting a quote by its ID

### ISSUE THREAD

**Issue by marekdano** [lukePeavey/quotable#5]
I'll be great if there is an API to get a quote by its ID. 

The suggested API:
 
### Request
```
https://api.quotable.io/quotes/:id
```

### Response
```
{
  _id: string,
  content: string, 
  author: string
}
```

**Comment by lukePeavey** [comment]
I think its a good idea, especially since there is a similar method for authors.

**Comment by lukePeavey** [comment]
If you want to work on this, that would awesome
