### ISSUE TITLE
API is currently down

### ISSUE THREAD

**Issue by roceb** [lukePeavey/quotable#62]
api.quotable.io is currently not working. Tried from multiple pc and IP address to verify. As well as checked isitdownrightnow.com to verify.

**Comment by lukePeavey** [comment]
Ok I'll look into this

**Comment by lukePeavey** [comment]
Yup, can confirm the server is partially down right now. I'll fix ASAP

**Comment by lukePeavey** [comment]
This has been fixed.  It was an issue with the DNSSEC configuration.  Let me know if it's working for you now. 

[isitdownrightnow](https://www.isitdownrightnow.com/api.quotable.io.html) shows the server as up

**Comment by roceb** [comment]
I can confirm, API is up and running. Thanks.

**Comment by Amitsharma45** [comment]
API is not working .

**Comment by roceb** [comment]
> API is not working .

I just double checked, working for me. What endpoint are you trying to hit?

**Comment by lukePeavey** [comment]
@Amitsharma45 Are you still having issues connecting to the API?  If you go to api.quotable.io in your browser, does the site load? 

[downfor.io/api.quotable.io](https://downforeveryoneorjustme.com/api.quotable.io)
[isitdownrightnow.com/api.quotable.io](https://www.isitdownrightnow.com/api.quotable.io.html)

**Comment by roceb** [comment]
Closed it since it seems to be up.

**Comment by lukePeavey** [comment]
@roceb thanks for reporting this!

**Comment by sandeepsaini309** [comment]
APIs are still down

**Comment by soam1** [comment]
still down https://www.isitdownrightnow.com/api.quotable.io.html
