### ISSUE TITLE
enhancement(/quotes): get quotes with author details 

### ISSUE THREAD

**Issue by dippas** [lukePeavey/quotable#63]
@lukePeavey  would be very handy if we could have the `link` (eventually the `bio`) on the `/quotes` endpoint

**Comment by raxraj** [comment]
@dippas, 
@lukePeavey 
Even I was thinking about this, I think it will add things to the project, as not only serving quotes but serving application requirements, where the user might need more info.

**Comment by lukePeavey** [comment]
@dippas @raxraj 
I have thought about this too. Getting a quote, or list of quotes, with the author details (like bio, description, profile image etc) is a common use case. I definitely agree it would be nice if you could do this with a single request.  

### How to do this with the current API

This is not really documented at the moment, so I just wanted to clarify how you would do this with the current API. It requires two requests: 

1) Make a request to `/quotes` endpoint to a get a list of quotes
2) Make a request to the `/authors` endpoint to get author details for each quote returned by the first request. The `/authors` endpoint has a `slug` parameter which can be used to get one or more authors by slug (this param has not been added to the docs yet).  To get multiple authors by slug, you provide a pipe-separated list of slugs. 

Here is an example function that gets a list of quotes, and includes the `Author` object with each result. The same approach could be used for the `/random` endpoint. 

```js
import { stringify } from 'query-string'

async function getQuotes(params = {}) {
  const API_URL = `https://api.quotable.io`
  // 1. Get a list of quotes
  const quotesResponse = await fetch(`${API_URL}/quotes?${stringify(params)}`)
  const { results: quotes, ...paginationInfo } = await quotesResponse.json()
  // 2. Get author details for each quote returned by the first request
  const authorSlugs = quotes.map(({ authorSlug }) => authorSlug).join('|')
  const authorsResponse = await fetch(`${API_URL}/authors?slug=${authorSlugs}`)
  const { results: authors } = await authorsResponse.json()
  // 3. Return the quotes response with the `Author` object included on each result
  return {
    ...paginationInfo,
    results: quotes.map(({ authorSlug, ...otherProperties }) => ({
      ...otherProperties,
      author: authors.find(author => author.slug === authorSlug),
    })),
  }
}
```

[![Edit Quotable - Get Quotes with Author Details](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/quotable-get-quotes-with-author-details-iyxw8?fontsize=14&hidenavigation=1&module=%2Fsrc%2Fapi.js&theme=dark)

**Comment by dippas** [comment]
@lukePeavey  yes I made this request because I'm making a block with quote of the day (a fun-sided project) and this feature would help me in order to make only one call to API

**Comment by lukePeavey** [comment]
I agree, it would be ideal if you could get quote(s) and the corresponding author(s) in a single request.

**Comment by raxraj** [comment]
@lukePeavey , fine assign this to me. I will work on this one.

**Comment by raxraj** [comment]
@lukePeavey ,
Are we going to work on this any time soon?

**Comment by lukePeavey** [comment]
Hey guys, 
If it's OK with you, I'd like to hold off on this for a bit.  I want to think a bit more about the best way to solve the underlying issue (how to get quotes and the corresponding author details) before we move ahead with making changes.

**Comment by raxraj** [comment]
On a second thought, I think the `quote` endpoint should not give polluted response.
It serves it's purpose.
Along with which it provides author ID I was wondering again, that do we really need that.

**Comment by raxraj** [comment]
@lukePeavey, on second thought,
I was just sitting thinking about a solution to this, Can we add another property to all the quotes returned. 
Something like this
```json
{
//    ..... All the Properties
     authorLink: "http://api.quotable.io/authors?slug=janis-joplin"
}
```

And then the end-product can get the author as per requirements.

**Comment by lukePeavey** [comment]
Wanted to circle back on this...

Ideally, I think that the `author` property on the quotes returned by the API should be the embedded `Author` object, rather than the author name.   This way the complete author data would be included in the response from the quotes endpoints. But this would require a breaking change. 

The current API does provide a way to get one or more quotes with the author details. And it only requires two API requests, regardless of the number of quotes.  The process is a little bit cumbersome, but you can easily build an API client that fetches quotes with the author details. So I feel like this is sufficient.

**Comment by lukePeavey** [comment]
I'm going to close this out since there has been any activity for a while.  If anyone has additional thoughts about this, feel free to start a Discussion.
