### ISSUE TITLE
AND filter is broken for tag based query 

### ISSUE THREAD

**Issue by kamransagheir** [lukePeavey/quotable#66]
The AND filer does not work. It just takes the first tag and returns quotes based on that i.e., if I do,  https://api.quotable.io/random?tags= famous-quotes,friendship or  https://api.quotable.io/random?tags=wisdom,friendship the API returns quotes based on, famous-quotes and wisdom respectively.

**Comment by lukePeavey** [comment]
Could you please provide more info
