### ISSUE TITLE
[Feature Request] Add tag(s) to quotes

### ISSUE THREAD

**Issue by marekdano** [lukePeavey/quotable#8]
I'm just considering to extend API with a new feature - selecting quotes by a tag name. But firstly each quote object has to contain *tag* or *tags* property in it. I'm not sure how hard is to add tag/tags to each quote since my English is not my native language. What do you think?

**Comment by lukePeavey** [comment]
I think this would be a great feature!  I will work on adding the additional metadata to the quotes, assigning one or more tags to each quote. Here is list of possible tags:

- famous-quotes
- life
- friendship
- science
- technology
- inspirational
- motivational
- literature 
- art
- business
- love
- success
- religion
- social-justice

In terms of the API, i think there should be a method to get a complete list of tags (ie `/tags`). And then we could add a parameter to the `/quotes` method to filter by tag name. Let me know what you think.

**Comment by marekdano** [comment]
Hi, @lukePeavey. I agree with your suggestions to have a new API of `/tags` for a list of tags and to modify existing `/quotes` to filter by tag name(s). I think we can have a param of *tags* that can have tag names separated by a comma, something like `/quotes?tags=love,art` or just have `/quotes?tag=love` for a single tag name. What do you think?

I'm open to help with APIs when tags are defined in each quote.

**Comment by lukePeavey** [comment]
@marekdano 

Sorry about the long delay. I've been really busy at work lately, so I haven't had much time to work on this.

I am still working on adding tags to all the existing quotes in the database. This is a pretty slow process, since it requires reading through the quotes and coming up with tags for each one (If anyone wants to help with this, let me know).

Anyway, I've added enough tags that we can move ahead with this feature.

**Comment by lukePeavey** [comment]
> I think we can have a param of tags that can have tag names separated by a comma.

I agree, the `tags` parameter should accept a list of one or more tags. I was thinking that it could support two types of lists: comma separated (for `AND`) or pipe `|` separated (for `OR`).

So a pipe separated list would match quotes that have `any` of the specified tags, whereas a comma separated list would match quotes with `all` the specified tags.

**Examples**

This would match quotes with tags "love" `OR` "friendship"

```
/quotes?tags=love|friendship
```

This would match quotes with the tags "famous-quotes" `AND` "technology"

```
/quotes?tags=famous-quotes,technology
```

**Comment by marekdano** [comment]
I like your suggestion, @lukePeavey! I can start working on it over my holidays.

**Comment by lukePeavey** [comment]
Sounds good!

**Comment by marekdano** [comment]
Is someone working on adding tags to quotes?

**Comment by marekdano** [comment]
@lukePeavey, thank you for adding tags to quotes! I'll work on API now.

**Comment by lukePeavey** [comment]
@marekdano Sounds good! 

Here is what we have left to do to complete this feature

- Add a `tags` field to the `Quote` schema
- Update `listQuotes`, `getQuoteById`, and `randomQuote` to include the `tags` field results
- Update the relevant tests
- Add the `tags` parameter to `randomQuote` and `listQuote`

One possible way to implement the `tags` filter would be something this...

```js
if (tags) {
  // If a `tags` parameter was provided
  if (tags.includes('|')) {
    // If `tags` is a pipe separated list (ie "art|music")...
    // match quotes that have either of the given tags
    filter.tags = { $in: tags.split('|') }
  } else {
    // If `tags` is a comma separated list or a single tag...
    // match quotes that have all of the given tags
    filter.tags = { $all: tags.split(',') }
  }
}

```

Let me know what you think

**Comment by marekdano** [comment]
@lukePeavey, I agree with your suggestions! I'm fully on it 😄.

**Comment by nonotest** [comment]
Hi guys,

is any extra help needed for this feature?

happy to contribute.

**Comment by lukePeavey** [comment]
@nonotest 

> is any extra help needed for this feature?

The only thing I know of that still needs to be done is updating [the documentation](https://github.com/lukePeavey/quotable#get-tags) for the `/tags` endpoint. It should include the following query parameters (added in #24).

- param: sortBy
    type: `enum: ["name", "quoteCount"]`
    description: The field used to sort tags. Default is name.

- param: sortOrder
    type: `enum: ["asc", "desc"]`
    description: The order in which results are sorted. Default order depends on the sortBy field.

**Comment by lukePeavey** [comment]
🚀Just deployed the latest changes, the should be live now :)

**Comment by lukePeavey** [comment]
@marekdano Great contribution!
