### ISSUE TITLE
HTTPS certificate

### ISSUE THREAD

**Issue by LuisFernandoLG** [lukePeavey/quotable#93]
## Description
I tried to fetch some data from my webapp, but the request failed, well it's just the https certificate.
Thnks c:

**Error:**
_"Mixed Content: The page at 'https://typing-applg.netlify.app/#/' was loaded over HTTPS, but requested an insecure resource 'http://staging.quotable.io/quotes?maxLength=200&minLength=100&limit=10'. This request has been blocked; the content must be served over HTTPS."_

**Comment by raxraj** [comment]
Hey @LuisFernandoLG,
You are using the staging version of the API, kindly try using `https://api.quotable.io/` in there. It must work fine.

**Comment by LuisFernandoLG** [comment]
Thnks c':

**Comment by lukePeavey** [comment]
@raxraj thanks!
