### ISSUE TITLE
Quotable DNS down?

### ISSUE THREAD

**Issue by adyanth** [lukePeavey/quotable#94]
**Describe the bug**
Quotable DNS domain seems to not have any records, causing all API requests to fail.

**To Reproduce**
See https://www.nslookup.io/dns-records/quotable.io#authoritative

**Comment by gigadeplex** [comment]
it's down again

**Comment by lukePeavey** [comment]
Maybe I'll check

**Comment by lukePeavey** [comment]
Yes it's down... will fix asap

**Comment by lukePeavey** [comment]
Fixed. May take a few hours to propagate. Sorry for the inconvenience

**Comment by lukePeavey** [comment]
![image](https://user-images.githubusercontent.com/8286271/147374971-875b32e3-1068-431d-baa8-a2ad0daade09.jpeg)
