### ISSUE TITLE
Search Author by name or keyword.

### ISSUE THREAD

**Issue by Mohammadshahzaib007** [lukePeavey/quotable#97]
## Description

There is no feature to search authors by their names, something like this.
`https://quotable.io/authors?searchKeyword=einstein`

If we hit the same endpoint with slug param it returns 0 (zero) results.
`https://api.quotable.io/authors?slug=einstein`

**Comment by lukePeavey** [comment]
There actually is a search feature, its just not documented.  I was planning to do some more work on it, so I think I was holding off on adding the docs until the API was finalized. 

We should definitely add it the docs so people can try it out.

**Comment by lukePeavey** [comment]
Here are the general docs for the current search feature. Feel free to try it out and let me know if you have any feedback. 

There are two search endpoints, one for authors and one for quotes.  They are powered by [Atlas Search](https://docs.atlas.mongodb.com/atlas-search/)


## Search Authors 

This endpoint allows you search for authors by name. It is intended to power a search bar with autocomplete suggestions. 

- Supports autocomplete mode
- Results are sorted by score, with best match at the top 
- Does not support searching for authors by other fields like `bio` or `description`

**Endpoint**

```HTTP
GET  /search/authors
``` 

**Query Parameters**

| Param       | Type                 | Description                                      |
| :--------- | :------------------ | :----------------------------------------------- |
| query    | `String` | The search query  |
| autocomplete    | `Boolean` | Enables autocomplete matching <br>  `default: true`  |
| matchThreshold  | `Int`     |   Sets the minimum number of search terms (words) that must match for an author to be included in results.  Basically, if this is set to 1, the results will include all authors that match at least part of the name. So if you search for "John F Kennedy" results would include all authors that match either "john" `OR` "kennedy". <br> If this is set to `2`, when the search query includes two or more "terms", at least two of those terms must match. So query="John F Kennedy" would only return authors that match "John" `AND` "Kennedy".  <br> `experimental` `default: 2` |
| limit | `Int`     |  Results per page    <br> `default: 20`  |
| page  | `Int`     | Page of results   <br> `default: 1`                    |

**Examples**
 
Search for author name "einstein" ([try in browser](https://api.quotable.io/search/authors?query=einstein))

```HTTP
GET /search/authors?query=einstein
```

Autocomplete search "John Ada" will match John Adams ([try in browswer](https://api.quotable.io/search/authors?query=john%20ada))
```HTTP
GET /search/authors?query=John Ada
```

## Search Quotes

This endpoint allows you to search for quotes by keywords, content, or author name.

- Search for quotes by `content`, `author`, and/or `tags`.  You can search by multiple fields simultaneously, or specify a specific search field (ie "author" to only search for quotes by author name). 
- Uses full-text search. This supports searching for keywords, phrases, or content.
- The results are sorted by score, with the best match at the top
- Search for an exact phrase by wrapping query in quotes. In this case it will only return quotes that match the query exactly. 

**Endpoint**

```HTTP
GET  /search/quotes
``` 

**Query Parameters**

| Param       | Type                 | Description                                      |
| :--------- | :------------------ | :----------------------------------------------- |
| query    | `String` | The search query  |
| fields    | `String` | Specify which fields to search by. Takes a comma separated list of field names. Supported fields are "content", "author", "tags".  You can search by multiple fields, or specify a single field. <br>  `default=content,author,tags`|
| limit | `Int`     |  Results per page    <br> `default: 20`  |
| page  | `Int`     | Page of results   <br> `default: 1`                    |

**Examples**

Search for a specific quote by content (does not need to be exact) ([try in browser](https://api.quotable.io/search/quotes?query=every+good+technology+is+basically+magic&fields=content))
```HTTP
GET /search/quotes?content=query=every good technology is basically magic"
```

Search for quotes matching the phrase "A divided house"
```HTTP
GET /search/quotes?query=A divided house
```

Search for quotes matching keywords "life" or "happiness" ([try in browser](https://api.quotable.io/search/quotes?query=life+happiness))

```HTTP
GET /search/quotes?query=life happiness
```

Search for quotes by author named "kennedy"  ([try in browser](https://api.quotable.io/search/quotes?query=kennedy&fields=author))

```HTTP
GET /search/quotes/query=Kennedy&fields=author
```

**Comment by lukePeavey** [comment]
@Mohammadshahzaib007 Sorry, I didn't notice you had closed this already before I commented. If you don't mind, I am going to re-open this since we need to add this feature to docs.

**Comment by Mohammadshahzaib007** [comment]
Ya sure @lukePeavey, you can reopen it.

**Comment by lukePeavey** [comment]
Does anyone want to submit a PR to add the search feature to documentation?
